server:
  port: 8180

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8181
              predicates:
                - Path=/api/v1/products/**

            - id: client-service
              uri: http://localhost:8182
              predicates:
                - Path=/api/v1/clients/**

