server:
  port: 8180

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: ${PRODUCT_SERVICE_URI:http://localhost:8181}
              predicates:
                - Path=/api/v1/products/**

            - id: client-service
              uri: ${CLIENT_SERVICE_URI:http://localhost:8182}
              predicates:
                - Path=/api/v1/clients/**

            - id: sales-service
              uri: ${SALES_SERVICE_URI:http://localhost:8183}
              predicates:
                - Path=/api/v1/sales/**

