server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none #using Liquibase for schema management
    properties:
      hibernate:
        default_schema: client_service
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
    default-schema: client_service