server:
  port: ${SERVER_PORT:8081}

spring:
  kafka:
    topics:
      products: products
      clients: clients
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL}
        auto.register.schemas: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none #using Liquibase for schema management
    properties:
      hibernate:
        default_schema: product_service
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
    default-schema: product_service