spring:
  jpa:
    hibernate:
      ddl-auto: none #using Liquibase for schema management
    properties:
      hibernate:
        default_schema: product_service
  liquibase:
    enabled: true
    change-log: classpath://db.changelog/changelog-master.yml
    default-schema: product_service